### ISSUE TITLE
请问后台账号密码是多少

### ISSUE THREAD

**Issue by vicowei** [DimpleFeng/DimpleBlog#1]
博主你好！后台的账号密码能提供一下吗？

**Comment by DimpleFeng** [comment]
你可以在com.dimple.framework.shiro.service.PasswordService路径下，有一个main方法可以对密码进行加密，生成的密码串覆盖到数据库的sys_user表中即可；
注意：第一个参数是账号，第二个参数是密码，第三个参数是盐。
