### ISSUE TITLE
前端页面怎么在webstorm运行起来，可以提供下相关教程或博客链接？

### ISSUE THREAD

**Issue by Weipiru** [DimpleFeng/DimpleBlog#14]

**Comment by skyls03** [comment]
thymelea分支是用的thymelea模板，在resource中，可以直接在浏览器中打开，新版本的前后端分离，要启动java后台才能访问

**Comment by Weipiru** [comment]
> thymelea分支是用的thymelea模板，在resource中，可以直接在浏览器中打开，新版本的前后端分离，要启动java后台才能访问

奥谢谢 已经运行起来了
