### ISSUE TITLE
请问前端代码build后访问不到

### ISSUE THREAD

**Issue by Weipiru** [DimpleFeng/DimpleBlog#16]
改了下vue的**配置文件**
` publicPath: process.env.NODE_ENV === "production" ? "/blog/" : "/",
 outputDir: 'blog',`
然后打包到blog目录，再放到Springboot resource下的static目录中 访问报404：

_OOPS!
版权所有 华尔街见闻
网管说这个页面你不能进......
请检查您输入的网址是否正确，请点击以下按钮返回主页或者发送错误报告_

是配置出问题了么

**Comment by DimpleFeng** [comment]
不清楚你为什么非要和SpringBoot联系在一起.
另外,前台后台前端代码全都是分离的,你注意别搞错了.
最后,这个分支的代码还在开发中,建议常人勿试
