### ISSUE TITLE
ip地址的服务替代

### ISSUE THREAD

**Issue by luoqingcheng** [DimpleFeng/DimpleBlog#18]
如题。这个ip地址的服务还有什么免费的替代吗？

**Comment by DimpleFeng** [comment]
最新的Vue版本的代码已经不使用淘宝的IP查询接口了。
使用以下依赖，具体使用教程参见其GitHub地址：
`        <dependency>
            <groupId>org.lionsoul</groupId>
            <artifactId>ip2region</artifactId>
            <version>1.7.2</version>
        </dependency>`

**Comment by DimpleFeng** [comment]
此外，目前还有一个免费的IP地址查询接口：http://whois.pconline.com.cn 
具体使用方法见网站介绍
