### ISSUE TITLE
请问后台主页的统计和曲线图怎么实现的？

### ISSUE THREAD

**Issue by AiMing317** [DimpleFeng/DimpleBlog#2]
请问后台主页的统计和曲线图怎么实现的？有没有其他样式的统计样式？例如柱状图。

**Comment by DimpleFeng** [comment]
采用百度开源Echarts制作，你可以去官网上看下小Demo：https://echarts.baidu.com/  在我的项目的templates/chart/business/business.html页面，有使用的方法，你可以研究下

**Comment by AiMing317** [comment]
JavaScript 实现的？那数据库中数据变化，曲线图会不会随着变化?

**Comment by DimpleFeng** [comment]
会变化呀，数据是从数据库中来的嘛。如果你要做到实时变化，那么就在前端设置一个定时器，定时多少秒去后端load数据过来就行了
