### ISSUE TITLE
请教一下，有些sql感觉好像错了

### ISSUE THREAD

**Issue by lianyuLJ** [DimpleFeng/DimpleBlog#20]
在mybatis映射文件FrontMapper.xml，有一个查询
<select id="selectSupportLinkList" resultType="com.dimple.project.system.domain.Link">
        select id, title, url, description, header_img
        from link
        where support = 1
        order by weight desc
    </select>
在link表里，找不到support字段，

**Comment by lianyuLJ** [comment]
<select id="selectSupportLinkList" resultType="com.dimple.project.system.domain.Link">
        select id, title, url, description, header_img
        from link
        where support = 1
        order by weight desc
    </select>

**Comment by ox123** [comment]
直接添加一下这个字段就可以跑起来了，亲测有效。
