### ISSUE TITLE
后端GUI执行npm run dev报错

### ISSUE THREAD

**Issue by ox123** [DimpleFeng/DimpleBlog#24]
当前front能够启动成功，
backend执行npm run dev 报错如下，百度和google各种办法都尝试了，还是有如下错误，是不是哪里版本不对呢？
当前环境版本：
**>npm -v
6.14.5**

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\babel-jest\node_modules\jest-haste-map\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

audited 2213 packages in 66.643s

33 packages are looking for funding
  run `npm fund` for details

found 434 vulnerabilities (409 low, 21 moderate, 4 high)
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by DimpleFeng** [comment]
You can ignore the warning or exec 'npm audit fix'.
this not bug.

**Comment by ox123** [comment]
useless, I have tried some ways like what you said.
