### ISSUE TITLE
管理后台的测试打不开新建文章页面

### ISSUE THREAD

**Issue by legendjslc** [DimpleFeng/DimpleBlog#26]
管理后台的测试打不开新建文章页面。点击“新建”， 会自动跳到404

**Comment by ox123** [comment]
遇到同样的问题，本地搭建也不能访问，查看权限都给了管理员权限

**Comment by legendjslc** [comment]
> 遇到同样的问题，本地搭建也不能访问，查看权限都给了管理员权限

![blog_add](https://user-images.githubusercontent.com/2969368/87637999-a285cc00-c775-11ea-9b58-ba936bb4876b.png)

查看路由也没有问题啊。好奇怪。

**Comment by ox123** [comment]
是不是在java端的代码某个地方做了限制呢

**Comment by DimpleFeng** [comment]
![image](https://user-images.githubusercontent.com/33685170/88031173-cf1f5680-cb6e-11ea-9dbd-629b562f2c61.png)
我的问题，请尝试修改图中路由地址：

**From blogManager to blogManage**

新增的路由地址在前端，具体地址是src/main/gui/backend/src/router/routers.js:101，两边保持一致即可。

**Comment by Punygod** [comment]
![image](https://user-images.githubusercontent.com/23066318/97102184-710a8e00-16de-11eb-92fc-db0b984850fc.png)
表示，参考了作者说的修改的，没用。哪里改的不对的吗？前端菜，求大神指教一二
