### ISSUE TITLE
关于图片管理 和留言管理 

### ISSUE THREAD

**Issue by laotouer** [DimpleFeng/DimpleBlog#4]
希望博主  关于 图片管理 和留言管理 能出一份说明帮助文档

**Comment by DimpleFeng** [comment]
留言采用畅言进行管理，过段时间会自研一套评论系统，畅言广告太多，很恶心。关于图片管理，图片使用七牛云作为图床进行保存，你也可以自己开发一个图片管理的功能。我觉得没必要就没有弄，因为图片也是占用带宽的，如果能用别人的服务器何乐而不为呢

**Comment by xjy626949690** [comment]
为啥在本地跑是好的,放到服务器上就读不出七牛云的图片

**Comment by DimpleFeng** [comment]
图片上传到七牛云后返回的应该是一个图片的地址链接吧，绝不会出现这种情况的，你看看你哪里配置有问题~
