### ISSUE TITLE
session存进Redis的问题

### ISSUE THREAD

**Issue by java-yan** [DimpleFeng/DimpleBlog#5]
pom依赖里有shiro-redis相关内容，shiro的配置中有没有相关配置开启shiro-redis啊？

**Comment by DimpleFeng** [comment]
Shiro相关缓存使用Ehcache，数据相关的内容才放在Redis中。之所以这样做一方面是为了分开用户认证缓存和数据缓存，另一方面，使用Redis缓存认证权限在某些情况下（比如启动应用的时候）会存在报错。还没有找到解决办法~
