### ISSUE TITLE
项目运行过程中会有好多数据库表缺少字段的情况，是不是sql导出的表结构不完整呀

### ISSUE THREAD

**Issue by b-eethoven** [DimpleFeng/DimpleBlog#7]
### Cause: java.sql.SQLSyntaxErrorException: Unknown column 'entry_url' in 'field list'
]

**Comment by b-eethoven** [comment]
目前的解决办法是删除sql中的字段，不影响运行，但是感觉怪怪的

**Comment by DimpleFeng** [comment]
好像是修改了SQL，等会我再重新更新下哈
