### ISSUE TITLE
启动项目报错

### ISSUE THREAD

**Issue by Espoir0** [DimpleFeng/DimpleBlog#8]
![image](https://user-images.githubusercontent.com/50947096/65750698-9889d280-e13b-11e9-9bc4-df41cd89f79c.png)

**Comment by Espoir0** [comment]
{"msg":"运行时异常:\r\n### Error querying database.  Cause: java.sql.SQLSyntaxErrorException: Unknown column 'b.allow_comment' in 'field list'\r\n### The error may exist in file [E:\\resourse\\code\\Github\\clone\\DimpleBlog\\target\\classes\\mybatis\\blog\\blog\\BlogMapper.xml]\r\n### The error may involve defaultParameterMap\r\n### The error occurred while setting parameters\r\n

### SQL: SELECT b.blog_id, b.category_id, b.title, b.summary, b.click, b.header_img, b.create_by, b.create_time, b.allow_comment, b.support, c.category_title, (SELECT count(*) FROM bg_comment WHERE page_id = b.blog_id AND display = 1) AS comment_count FROM bg_blog b LEFT JOIN bg_category c ON b.category_id = c.category_id WHERE status = 1 order by create_time desc LIMIT ?\r\n

### Cause: java.sql.SQLSyntaxErrorException: Unknown column 'b.allow_comment' in 'field list'\n;

 bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Unknown column 'b.allow_comment' in 'field list',
日志标识： 1569569177518","code":500}

**Comment by DimpleFeng** [comment]
> {"msg":"运行时异常:\r\n### Error querying database. Cause: java.sql.SQLSyntaxErrorException: Unknown column 'b.allow_comment' in 'field list'\r\n### The error may exist in file [E:\resourse\code\Github\clone\DimpleBlog\target\classes\mybatis\blog\blog\BlogMapper.xml]\r\n### The error may involve defaultParameterMap\r\n### The error occurred while setting parameters\r\n
> 
> ### SQL: SELECT b.blog_id, b.category_id, b.title, b.summary, b.click, b.header_img, b.create_by, b.create_time, b.allow_comment, b.support, c.category_title, (SELECT count(*) FROM bg_comment WHERE page_id = b.blog_id AND display = 1) AS comment_count FROM bg_blog b LEFT JOIN bg_category c ON b.category_id = c.category_id WHERE status = 1 order by create_time desc LIMIT ?\r\n
> ### Cause: java.sql.SQLSyntaxErrorException: Unknown column 'b.allow_comment' in 'field list'\n;
> bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Unknown column 'b.allow_comment' in 'field list',
> 日志标识： 1569569177518","code":500}

你在blog表中加入一列allow_comment就好了，这个列主要用于控制文章是否允许评论
